services:
  db:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "2222:22"
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
