FROM postgres:17-alpine

RUN apk add --no-cache openssh-server && \
    ssh-keygen -A && \
    adduser -D -s /bin/sh challenge && \
    echo "challenge:challenge" | chpasswd && \
    echo "CREATE ROLE challenge WITH LOGIN CREATEDB PASSWORD 'challenge';" \
      > /docker-entrypoint-initdb.d/init.sql

EXPOSE 22

ENTRYPOINT ["/bin/sh", "-c", "/usr/sbin/sshd && exec docker-entrypoint.sh \"$@\"", "--"]
CMD ["postgres"]
