services:
  ssh:
    build:
      context: ./docker/ssh
      args:
        SSH_USER: appuser
        SSH_PASSWORD: appuser
        PG_PASSWORD: appuser
    container_name: pdm_ssh
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - pdm_postgres_data:/var/lib/postgresql/15/main

volumes:
  pdm_postgres_data:
